<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <Deterministic>true</Deterministic>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Configurations>Debug;Release;EasyTest</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Controllers\Entities\**" />
    <EmbeddedResource Remove="Controllers\Entities\**" />
    <None Remove="Controllers\Entities\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Controllers\DXViewController.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Model.DesignedDiffs.xafml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Model.DesignedDiffs.xafml" />
    <EmbeddedResource Include="Images\*.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp" Version="26.1.4" />
    <PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" Version="26.1.4" />
    <PackageReference Include="DevExpress.ExpressApp.ConditionalAppearance" Version="26.1.4" />
    <PackageReference Include="DevExpress.ExpressApp.Xpo" Version="26.1.4" />
    <PackageReference Include="DevExpress.ExpressApp.Security.Xpo" Version="26.1.4" />
    <PackageReference Include="DevExpress.ExpressApp.Validation" Version="26.1.4" />
    <PackageReference Include="DevExpress.Persistent.Base" Version="26.1.4" />
    <PackageReference Include="DevExpress.Persistent.BaseImpl.Xpo" Version="26.1.4" />
    <PackageReference Include="DevExpress.Xpo" Version="26.1.4" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.10.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.10.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.10.0">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.18" NoWarn="NU1510" />
  </ItemGroup>
</Project>
