<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp" Version="26.1.4" />
    <PackageReference Include="DevExpress.Persistent.Base" Version="26.1.4" />
    <PackageReference Include="DevExpress.Xpo" Version="26.1.4" />
    <PackageReference Include="FluentAssertions" Version="7.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project1.Core\Project1.Core.csproj" />
    <ProjectReference Include="..\Project1.DTOs\Project1.DTOs.csproj" />
    <ProjectReference Include="..\Project1.Module\Project1.Module.csproj" />
  </ItemGroup>

</Project>